config/routes.rb
SmsBackup::Application.routes.draw do

  root to: 'accounts#index'

  resources :accounts, only: :index do
    resources :conversations, :path => '/', only: :index do
      resources :messages, :path => '/'
    end
  end

  resources :messages, only: [:create]
  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  self.inheritance_column = nil

  validates_uniqueness_of :message_id, scope: :android_id
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  expose(:accounts) do
    Message.select(:android_id).map(&:android_id).compact.uniq
  end

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  skip_before_action :verify_authenticity_token
  respond_to :html, :json

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:phone_number, :name)
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  expose(:account) do
    params[:account_id]
  end

  expose(:conversations) do
    Message.where(android_id: params[:account_id]).select(:address).map(&:address).uniq
  end

  def index
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  expose(:message)
  expose(:messages) do
    Message.where(android_id: params[:account_id], address: params[:conversation_id]).reverse
  end

  def create
    if params[:messages].present?
      params[:messages].each do |message|
        Message.create(message)
      end

      count = messages.count
      render status: 200, json: "OK"
    else
      message.save
      respond_with(message)
    end
  end

  def update
    message.save
    respond_with(message)
  end

  def destroy
    message.destroy
    respond_with(message)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/accounts/index.html.haml
%h1 Listing Accounts

%table.table
  %thead
    %tr
      %th Accounts

  %tbody
    - accounts.each do |a|
      %tr
        %td
          = link_to a, account_conversations_path(a)

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Phone number</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.phone_number %></td>
        <td><%= contact.name %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone number:</strong>
  <%= @contact.phone_number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/conversations/index.html.haml
%h1 Listing conversations

%table.table
  %thead
    %tr
      %th Conversations

  %tbody
    - conversations.each do |c|
      %tr
        %td
          = link_to c, account_conversation_messages_path(account, c)

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "SmsBackup"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") SmsBackup
          .container.nav-collapse
            %ul.nav
              %li= link_to "Accounts", accounts_url

    .container{id: "navbar-fix"}

      .row
        .span12
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Company 2013

app/views/messages/index.html.haml
%h1.centered Contacts name

.row
  .span4.offset4
    .messages
      - messages.each do |message|
        .message{class: [(('sent' unless message.type == 1) or 'recieved'), 'span3']}
          = message.message
          .time
            = (time_ago_in_words(message.sent_at) rescue 'unknown time') + " ago"